In [93]:
import numpy as np

docs = ['go pakistan',
		'pakistan pakistan',
		'hip hip hurray',
		'jeetega bhai jeetega pakistan jeetega',
		'Dil Dil Pakistan',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'Imran khan zindabad',
		'inquilab zindabad']

In [94]:
# now we tokenize our whole content mean word by word sep capital to small remove special symbols
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token="<nothing>") # out of vocablury mean if new word come that is not in our dict replace it with nothing

In [95]:
tokenizer.fit_on_texts(docs) # reg 189

In [96]:
tokenizer.word_index #we can see which number is assign

{'<nothing>': 1,
 'pakistan': 2,
 'jeetega': 3,
 'hip': 4,
 'dil': 5,
 'kohli': 6,
 'sachin': 7,
 'dhoni': 8,
 'zindabad': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'imran': 13,
 'khan': 14,
 'inquilab': 15}

In [97]:
tokenizer.word_counts # which word come how many time

OrderedDict([('go', 1),
             ('pakistan', 5),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('dil', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('imran', 1),
             ('khan', 1),
             ('zindabad', 2),
             ('inquilab', 1)])

In [98]:
tokenizer.document_count # how many total sentences

10

In [99]:
# now the numbers assigned are in indexing shape
sequence = tokenizer.texts_to_sequences(docs)

In [100]:
sequence # 10 for go 2 for pakistan

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [5, 5, 2],
 [6, 6],
 [7, 7],
 [8, 8],
 [13, 14, 9],
 [15, 9]]

In [101]:
# now we apply padding as on reg
from keras.utils import pad_sequences
sequence = pad_sequences(sequence,padding='post') # post mean add 0 at the end

In [102]:
sequence # now the shape is ready

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [ 5,  5,  2,  0,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [13, 14,  9,  0,  0],
       [15,  9,  0,  0,  0]], dtype=int32)

now we use this on large dataset

In [103]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import *

In [104]:
(x_train,y_train),(x_test,y_test) = imdb.load_data()

In [105]:
x_train[0] # if we se the shape it is alrwady in vectors

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [106]:
# now we make all the reviews length equal
from tensorflow.keras.preprocessing.sequence import pad_sequences
x_train = pad_sequences(x_train,maxlen=50) #mean max legth of sentence is 50
x_test = pad_sequences(x_test,maxlen=50)  # add pooling

In [107]:
x_train.shape,len(x_test[0]) #now  total length is 50 of all sentences

((25000, 50), 50)

In [108]:
x_train[0]


array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [109]:
from keras.layers import Dense,SimpleRNN,Flatten # see page no 190
model = Sequential()
model.add(SimpleRNN(32,input_shape = (50,1),return_sequences=False)) # shape mean 50 timpe step 1 input feature
# return sewquence mean if we want output at every time step outside if we false it mean it become inside the model and come when final output comes
model.add(Dense(1,activation="sigmoid"))
model.summary() # structure explain on reg 190 page no

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_20"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)             │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [110]:
model.compile(loss= "binary_crossentropy",optimizer = "adam",metrics = ["accuracy"])

In [111]:
model.fit(x_train,y_train,epochs = 5,validation_data= (x_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 14ms/step - accuracy: 0.5000 - loss: 0.6943 - val_accuracy: 0.5014 - val_loss: 0.6933
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.5040 - loss: 0.6934 - val_accuracy: 0.5037 - val_loss: 0.6929
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - accuracy: 0.5053 - loss: 0.6932 - val_accuracy: 0.5068 - val_loss: 0.6932
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 15ms/step - accuracy: 0.5088 - loss: 0.6931 - val_accuracy: 0.5062 - val_loss: 0.6940
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 16ms/step - accuracy: 0.5018 - loss: 0.6932 - val_accuracy: 0.5016 - val_loss: 0.6952


In [112]:
# not give good results but our main focus is how to implement rnns not achieve the best accuracy

embedding tehnique


In [113]:
# to easy to apply embedding layer in keras just make sure data must be integer encoded
# om reg pg 90  explain


In [114]:
 import numpy as np

docs = ['go pakistan',
		'pakistan pakistan',
		'hip hip hurray',
		'jeetega bhai jeetega pakistan jeetega',
		'Dil Dil Pakistan',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'Imran khan zindabad',
		'inquilab zindabad']

In [115]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [116]:
tokenizer.fit_on_texts(docs)

In [117]:
len(tokenizer.word_index)

14

In [118]:
sequence = tokenizer.texts_to_sequences(docs)

In [119]:
sequence # now sequnce is generated

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [4, 4, 1],
 [5, 5],
 [6, 6],
 [7, 7],
 [12, 13, 8],
 [14, 8]]

In [120]:
from tensorflow.keras.utils import pad_sequences

In [121]:
sequence = pad_sequences(sequence,padding='post')


In [122]:
sequence

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [ 4,  4,  1,  0,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [12, 13,  8,  0,  0],
       [14,  8,  0,  0,  0]], dtype=int32)

now our main work mean embedding starts

In [123]:
model = Sequential()
model.add(Embedding(14,output_dim=2,input_length=5)) # 14 our total unique word input length mean length of sentence
model.summary()

Model: "sequential_21"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_16 (Embedding)             │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

donot work lets see throgh diff example

In [124]:
import tensorflow
from tensorflow import keras
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,Flatten,SimpleRNN


In [125]:
(x_train,y_train),(x_test,y_test) = imdb.load_data()

In [126]:
x_train = pad_sequences(x_train,padding = 'post',maxlen= 50)
x_test = pad_sequences(x_test,padding = 'post',maxlen= 50)

In [127]:
x_train.shape,x_test.shape

((25000, 50), (25000, 50))

In [128]:
model = Sequential()
model.add(Embedding(10000,output_dim=2,input_length=50)) #2 mean every one word in divided into two words 10000 is our total unique words
# 50 is our total len of sentence
model.add(SimpleRNN(32,return_sequences=False)) # explain  above
model.add(Dense(1,activation='sigmoid'))

In [129]:
model.summary()

Model: "sequential_22"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_17 (Embedding)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_4 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)